[project]
name = "repovitals"
version = "0.1.0"
description = "tool to health check pip dependencies & analyze git repo patterns"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Mustafa Bukhari M. Ahmed", email = "mustafa.bukh@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.urls]
Homepage = "https://github.com/mustafabukhari/repovitals"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

